apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipeline-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: image-registry
      value: "us.icr.io/<your_namespace>/tax-calculator:latest"
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: app-pvc
